CXX := mpicxx
CXXFLAGS := -std=c++11 -Ofast -march=corei7
OPT_CXXFLAGS := ${CXXFLAGS} -funroll-all-loops

INC := -I${MKL_INC}

LIBS := ${MKL}

BUILDNAME := meamz-carver
OBJDIR := build
SRCDIR := src

include _makefile
